name: CI

on: [pull_request]

jobs:
  trivial-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trivially pass
        run: echo "All tests passed!"

